[build]
  command = "npm build"
  publish = "public"

# build a preview of the site (Drafts and Future dates also)
[context.deploy-preview]
  command = "npm build:preview"

# build a staging build for the `staging` branch
[context.staging]
  command = "npm build:stage"
